### ISSUE TITLE
Running PX4 Simulation in Real-Time

### ISSUE THREAD

**Issue by ranjithlesoko** [Zhefan-Xu/autonomous_flight#2]
I've been working with PX4 simulation and have found it to be effective. However, I'm interested in exploring how to run the simulation in real-time for more accurate testing and analysis. I would appreciate any guidance or instructions on configuring PX4 simulation to operate in real-time mode.

**Comment by ranjithlesoko** [comment]
I've configured PX4 with a RealSense D435i camera and Pixhawk 6 Mini on my Jetson NX Xavier for real-time operation. While I've completed all necessary configurations, I'm encountering performance issues, particularly with low FPS. I'm seeking guidance on improving real-time performance on the Jetson NX Xavier platform. Specifically, I'm interested in optimizing FPS and ensuring smooth operation of the system. Additionally, I would appreciate any advice on leveraging frameworks or optimizations to enhance real-time performance with this setup

**Comment by Zhefan-Xu** [comment]
@ranjithlesoko Hi, thanks for the info:
1. what do you mean by run the simulation in real-time? This simulation should already run in real-time.
2. Hardware is tricky. It is very difficult to figure out the problem based on just your descriptions.

**Comment by ranjithlesoko** [comment]
how to run your framework in realtime? help me to make a launch file for hardware side and realtime testing

**Comment by ranjithlesoko** [comment]
Hello @Zhefan-Xu, I'm exploring your framework and intrigued by its usage of the VINS (Visual-Inertial Odometry) estimator. Could you please provide guidance on running your framework on a Jetson device? Upon reviewing your code, I noticed the implementation of VINS estimator, which seems particularly interesting. Any assistance you could offer in this regard would be greatly appreciated.

**Comment by Zhefan-Xu** [comment]
Please refer to this repo: https://github.com/HKUST-Aerial-Robotics/VINS-Fusion
